name: app_evo_movies
description: "Projeto Flutter para o desáfio técnico da Evo Systems."

environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0

flutter:
  uses-material-design: true